version: "3"
services:
  minecraft:
    ports:
      - "25565:25565"
      - "25575:25575"
    image: itzg/minecraft-server:latest
    restart: always
    environment:
      EULA: "TRUE"
      OVERRIDE_OPS: "true"
    stdin_open: true
    tty: true

  discord-bot:
    image: ajvreugdenhil/minecraftstatusbot:nightly
    restart: on-failure
    environment:
      SERVER_URL: "example.com"
      LOCAL_IP: "minecraft"
      QUERY_PORT: 25565
      RCON_PORT: 25575
      RCON_PASSWORD: "xxxxxxxxxxxxxxx"
      DISCORD_TOKEN: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      DISCORD_CHANNEL_NAME: "botchannel"
    depends_on:
      - minecraft
    links:
      - minecraft
    stdin_open: true
    tty: true
